### ISSUE TITLE
timeout issue

### ISSUE THREAD

**Issue by spurnaye** [JuliaLang/METADATA.jl#5213] opened 2016-05-18 17:48 UTC
Hello,
When I am trying to install any package, I am seeing following issue
```
ERROR: failed process: Process(`git clone -q -b metadata-v2 git://github.com/JuliaLang/METADATA.jl METADATA`, ProcessExited(128)) [128]
[APP_PATH] /Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in anonymous at pkg/dir.jl:52
 in cd at [APP_PATH]/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in init at pkg/dir.jl:50
 in cd at pkg/dir.jl:28
 in add at pkg.jl:23
```

**Comment by spurnaye** [comment] 2016-05-18 17:52
manual command is not working 
```
git clone -q -b metadata-v2 git://github.com/JuliaLang/METADATA.jl METADATA
```

**Comment by tkelman** [comment] 2016-05-18 19:45
Does it work with any other github repositories? I'm going to close this as a duplicate of https://github.com/JuliaLang/julia/issues/14616, and more of a git issue than a Metadata or Julia one. Do you happen to use zsh by any chance?

**Closed by tkelman** 2016-05-18 19:45 UTC
