### ISSUE TITLE
PkgDev.publish()    :    packages with unsatisfiable requirements found:     Mads v0.3.3 – no valid versions exist for package FileIO

### ISSUE THREAD

**Issue by chkwon** [JuliaLang/METADATA.jl#8005] opened 2017-02-17 18:59 UTC
I tested with a fresh package directory. While `Pkg.update()` does not create any problem, but `PkgDev.publish()` does. 

I do have neither `Mads` nor `FileIO` installed, but they crash.

```julia
julia> Pkg.status()
INFO: Initializing package repository /Users/chkwon/.julia/v0.5
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
No packages installed

julia> 

julia> Pkg.clone("https://github.com/chkwon/PATHSolver.jl.git")
INFO: Cloning PATHSolver from https://github.com/chkwon/PATHSolver.jl.git
INFO: Computing changes...
INFO: Installing BinDeps v0.4.5
INFO: Installing Calculus v0.2.0
INFO: Installing Compat v0.18.0
INFO: Installing DiffBase v0.0.4
INFO: Installing ForwardDiff v0.3.4
INFO: Installing NaNMath v0.2.2
INFO: Installing SHA v0.3.1
INFO: Installing URIParser v0.1.8
INFO: Package database updated

julia> Pkg.add("PkgDev")
INFO: Installing JSON v0.8.3
INFO: Installing PkgDev v0.1.3
INFO: Package database updated

julia> using PkgDev; PkgDev.tag("PATHSolver", :minor)
INFO: Recompiling stale cache file /Users/chkwon/.julia/lib/v0.5/PkgDev.ji for module PkgDev.
INFO: Tagging PATHSolver v0.2.0
INFO: Committing METADATA for PATHSolver

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating PATHSolver master...
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> Pkg.status()
2 required packages:
 - PATHSolver                    0.2.0              master
 - PkgDev                        0.1.3
9 additional packages:
 - BinDeps                       0.4.5
 - Calculus                      0.2.0
 - Compat                        0.18.0
 - DiffBase                      0.0.4
 - ForwardDiff                   0.3.4
 - JSON                          0.8.3
 - NaNMath                       0.2.2
 - SHA                           0.3.1
 - URIParser                     0.1.8

julia> PkgDev.publish()
INFO: Validating METADATA
ERROR: packages with unsatisfiable requirements found:
    Mads v0.3.3 – no valid versions exist for package FileIO

 in check_metadata(::Set{String}) at /Users/chkwon/.julia/v0.5/PkgDev/src/entry.jl:301
 in (::PkgDev.Entry.##4#9{String,Dict{String,Array{String,1}},String})(::Base.LibGit2.GitRepo) at /Users/chkwon/.julia/v0.5/PkgDev/src/entry.jl:93
 in with(::PkgDev.Entry.##4#9{String,Dict{String,Array{String,1}},String}, ::Base.LibGit2.GitRepo) at ./libgit2/types.jl:638
 in publish(::String, ::String) at /Users/chkwon/.julia/v0.5/PkgDev/src/entry.jl:64
 in publish() at /Users/chkwon/.julia/v0.5/PkgDev/src/PkgDev.jl:70
```

**Comment by tkelman** [comment] 2017-02-17 19:11
what's your julia `versioninfo()` ?

**Comment by tkelman** [comment] 2017-02-17 19:13
https://github.com/JuliaLang/METADATA.jl/pull/8006 might help, or in the meantime you can use https://github.com/attobot/attobot

**Comment by chkwon** [comment] 2017-02-17 19:38
@tkelman 

```
julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)
```

**Comment by chkwon** [comment] 2017-02-17 19:44
@tkelman  `attobot` looks cool!

**Comment by tkelman** [comment] 2017-02-17 19:53
I'm not able to reproduce the resolution failure, when did you run this?

**Comment by chkwon** [comment] 2017-02-17 19:59
@tkelman about an hour ago.

**Comment by haberdashPI** [comment] 2017-02-21 21:11
I'm having the same problem.

**Comment by tkelman** [comment] 2017-02-21 21:29
what commit of metadata are you at?

**Comment by haberdashPI** [comment] 2017-02-21 22:13
cebb416cc6b2dae2902202812189e1fa52f20df5

**Comment by tkelman** [comment] 2017-02-21 22:23
And what's your `git status` in METADATA? If I do `cp -r Weber/versions/0.3.6 Weber/versions/0.3.7 && cd .. && julia METADATA/.test/METADATA.jl` then everything works fine for me. Assuming you haven't changed the REQUIRE since your last tag, the consistency check shouldn't care what the sha's are.

**Comment by haberdashPI** [comment] 2017-02-22 01:47
I haven't changed REQUIRE. Here's output of `git status`:

```julia
On branch metadata-v2
Your branch is ahead of 'origin/metadata-v2' by 1 commit.
  (use "git push" to publish your local commits)
nothing to commit, working tree clean
```

Calling `julia METADATA/.test/METADATA.jl` (in ~/.julia/v0.5) yields:

```julia
INFO: Checking that all entries in METADATA are recognized packages...
INFO: Verifying METADATA...
INFO: Nothing to be done
INFO: METADATA is out-of-date — you may not have the latest version of PkgDev
INFO: Use `Pkg.update()` to get the latest versions of your packages
ERROR: LoadError: packages with unsatisfiable requirements found:
    Mads v0.3.3 – no valid versions exist for package FileIO

 in check_metadata(::Set{String}) at /Users/davidlittle/.julia/v0.5/PkgDev/src/entry.jl:301
 in check_metadata() at /Users/davidlittle/.julia/v0.5/PkgDev/src/entry.jl:288
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
 in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Users/davidlittle/.julia/v0.5/METADATA/.test/METADATA.jl, in expression starting on line 248
```
A call to `Pkg.update()` yields:

```julia
INFO: Updating METADATA...
INFO: Updating Weber master...
INFO: Computing changes...
INFO: No packages to install, update or remove
```

**Comment by tkelman** [comment] 2017-02-22 02:10
Could you push that metadata commit to your fork? I can't reproduce this at the moment.

**Comment by haberdashPI** [comment] 2017-02-22 16:06
After updating from branch `metadata-v2` again I am no longer getting this error anymore. I can try using a different value JULIA_PKGDIR and see if I can reproduce the problem again to help you fix any bug that might be causing this.

**Comment by tkelman** [comment] 2017-02-22 16:26
I know what bug is causing this (it's a Pkg resolver issue that `@carlobaldassi` fixed on master recently), but it won't be easily fixable until 0.5.1 is ready and everyone who hits this problem upgrades to it (or switches to using attobot). The question is whether any workarounds are needed to keep 0.5.0 functional for those who can't/won't upgrade or use attobot. Applying a few additional bounds in specific places can suppress this, but it's best to be able to reproduce the issue to determine the right bounds to adjust.

**Comment by haberdashPI** [comment] 2017-02-22 16:30
Okay. Glad to hear it will be fixed whenever 0.5.1 gets released! I guess my offer still stands: would it be at all helpful for you if I try and reproduce my particular example of this problem so that some additional bounds can be added?

**Comment by tkelman** [comment] 2017-02-22 16:31
It would, since I suspect this is going to keep happening.

**Comment by chkwon** [comment] 2017-02-22 17:26
@tkelman I'm also glad. By the way, is it possible to have something like `PkgDev.publish("PackageName")`?

**Comment by tkelman** [comment] 2017-05-10 09:24
the known resolver issues should be fixed in 0.5.1 and/or 0.5.2

**Closed by tkelman** 2017-05-10 09:24 UTC

**Comment by djsegal** [comment] 2017-11-22 03:18
I get:

```julia
julia> PkgDev.publish()
INFO: No new package versions to publish
INFO: Validating METADATA
ERROR: packages with unsatisfiable requirements found:
    DiffEqDevTools v0.7.0 – no valid versions exist for package DiffBase
    DiffEqDevTools v0.7.1 – no valid versions exist for package DiffBase
```

**Comment by KristofferC** [comment] 2017-11-22 08:15
cc @ChrisRackauckas

**Comment by ChrisRackauckas** [comment] 2017-11-22 09:13
DiffEqDevTools doesn't depend on DiffBase, even indirectly. It also hasn't been tagged in quite awhile. So I think that's a false hit.

**Comment by KristofferC** [comment] 2017-11-22 09:21
Another report https://github.com/JuliaLang/METADATA.jl/issues/12139.

False or not, I guess we need to do something because it seems METADATA is currently broken (or falsely detected as broken).

**Comment by carlobaldassi** [comment] 2017-11-22 10:09
I'll look into this as soon as I can (probably tomorrow). In the meanwhile, any instructions to reproduce are welcome.

**Comment by carlobaldassi** [comment] 2017-11-22 13:20
@djsegal could you please tell me
1. What was your METADATA commit
2. What was the change that you were trying to publish

Thanks

**Comment by carlobaldassi** [comment] 2017-11-22 21:01
@djsegal can you try setting 

```
ENV["JULIA_PKGRESOLVE_ACCURACY"]=2
```

and see if the problem goes away?

**Comment by djsegal** [comment] 2017-11-23 03:15
Never did that. Fixed problem on two computers doing:

```julia
Pkg.add("DiffEqDevTools")
Pkg.checkout("DiffEqDevTools")
```
